[tool.poetry]
name = "nearai"
version = "0.1.0"
description = ""
authors = ["Marcelo Fornet <mfornet94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
fire = "^0.6.0"
flask = "^3.0.3"
boto3 = "^1.34.100"
boto3-stubs = "^1.34.100"
datasets = "^2.19.1"
transformers = "^4.40.2"
peft = "^0.10.0"
torch = "^2.2.2"
fabric = "^3.2.2"
gunicorn = "^22.0.0"
requests = "^2.31.0"
pymysql = "^1.1.0"
setuptools = "^69.5.1"
backoff = "^2.2.1"
tabulate = "^0.9.0"
tqdm = "^4.66.4"
pydantic = "^2.7.1"
openai = "^1.30.1"
jinja2 = "^3.1.4"
litellm = "^1.41.0"
tenacity = "^8.2.3"
torchtune = { git = "https://github.com/pytorch/torchtune.git#58d58bce65836c23865e6a9aa683475631527d82" }
torchao = { git = "https://github.com/pytorch/ao.git#a8956992191853b13f82ceb3e6929bed7691a3fa" }
tensorboardX = "^2.6.2.2"
vllm = "^0.5.0.post1"
fastapi = "^0.111.0"
fastapi-cli = "^0.0.4"
python-dotenv = "^1.0.1"
pydantic-core = "^2.18.4"
base58 = "2.1.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
ruff = "^0.5.2"

[tool.poetry.scripts]
nearai = "nearai.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = [
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "venv",
]
extend-exclude = ["tests"]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "N",  # PEP8 naming conventions
    "D"   # pydocstyle
]
ignore = [
    "C901",  # too complex
    "C408",  # dict() constructor
    "C417",  # enforce list comprehension
    "W191",  # indentation contains tabs
    "D401",  # imperative mood
    "D100",  # Missing docstring module
    "D101",  # Missing docstring in public class
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public package
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_generics = false
disallow_any_explicit = false
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_redundant_casts = true
strict_equality = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ['datasets.*', 'fire.*']
ignore_missing_imports = true
