[tool.poetry]
name = "jasnah"
version = "0.1.0"
description = ""
authors = ["Marcelo Fornet <mfornet94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fire = "^0.6.0"
flask = "^3.0.3"
boto3 = "^1.34.100"
boto3-stubs = "^1.34.100"
datasets = "^2.19.1"
transformers = "^4.40.2"
peft = "^0.10.0"
torch = "^2.2.2"
fabric = "^3.2.2"
gunicorn = "^22.0.0"
requests = "^2.31.0"
pymysql = "^1.1.0"
setuptools = "^69.5.1"
backoff = "^2.2.1"
tabulate = "^0.9.0"
tqdm = "^4.66.4"
pydantic = "^2.7.1"
openai = "^1.30.1"
jinja2 = "^3.1.4"
litellm = "^1.41.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pylint = "^2.15.5"
mypy = "^1.10.0"

[tool.poetry.scripts]
jasnah-cli = "jasnah.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_generics = false
disallow_any_explicit = false
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_redundant_casts = true
strict_equality = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ['datasets.*', 'fire.*']
ignore_missing_imports = true

[tool.black]
line-length = 100
target-version = ['py39']
