version: '3.8'

services:
  guest_manager:
    build:
      context: ../..
      dockerfile: tee_infra/guest_manager/Dockerfile
      args:
        BUILD_TIMESTAMP: ${BUILD_TIMESTAMP:-}
    image: guest_manager:latest
    container_name: guest_manager
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUST_LOG=info
    restart: unless-stopped
