services:
  nearai_dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.gpu.dev
    network_mode: host
    volumes:
      - ..:/workspace:Z
      - ~/.nearai:/home/user/.nearai
      - ~/.cache:/home/user/.cache
    command: "sleep infinity"
    platform: linux/amd64

    ## Comment out to remove gpu devices
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]